#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /Users/admin/Documents/tomcat/
#  file: /Users/admin/Documents/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.20.10.3/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 172.20.10.3
    port: 6379
server:
  context-path: /sell
  port: 80



wechat:
  mpAppId: wxc8951dba20e8ba76
  mpAppSecret: caff618149de3e744ac6beab42047bc1
  openAppId: wwwwwwwwwwwwwwwwww
  openAppSecret: wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
  mchId: 1409146202
  mchKey: c9734132412341234
  keyPath: /Users/admin/Desktop
  notifyUrl: http://weilining.ml/sell/pay/notify

projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc